baseURL: "https://mettaconseil.com"
defaultContentLanguage: "fr"
languageCode: "fr"
title: "Metta Conseil"
canonifyURLs: false
relativeURLs: true
disableFastRender: true
disableLiveReload: true
metaDataFormat: yaml
rssLimit: 10
enableRobotsTXT: true
params:
  description: "Conseil en Organisation et Systèmes d'Information"
  author: "Victor Massé"
author:
  name: "Victor Massé"
taxonomies:
  category: categories
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: false
  tableOfContents:
    startLevel: 1
    endLevel: 5
footnoteReturnLinkContents: "↑"
menu:
  main:
    - Name: "Accueil"
      URL: "/"
      Identifier: "accueil"
      weight: 1
    - Name: "Prestations"
      URL: "/prestations/"
      Identifier: "prestations"
      weight: 2
    - Name: "Tarifs"
      URL: "/tarifs/"
      Identifier: "tarifs"
      weight: 3
    - Name: "Clients"
      URL: "/clients/"
      Identifier: "clients"
      weight: 4
    - Name: "À propos"
      URL: "/a-propos/"
      Identifier: "a-propos"
      weight: 5
  footer:
    - Name: "Mentions légales"
      URL: "/mentions-legales/"
      Identifier: "mentions-legales"
      weight: 1
